import Head from 'next/head';
import styled from 'styled-components';
import Bigblock from '../components/bigblock';
import Primarybutton from '../components/primarybutton';

const Wrapper = styled.div`
  height: 100%;
  width: 100%;
  padding: 5px 10px;
  position: relative;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Wrapper>
       <Bigblock 
        topline='Hello World'
        middleline='welcome to'
        bottomline='my'
        lighttext='world'
       />
       <Primarybutton
        content='Learn More'
       />
      </Wrapper>   
    </>
  )
}
