import Head from 'next/head';
import styled from 'styled-components';
import Bigblock from '../components/bigblock';
import Primarybutton from '../components/primarybutton';
import Fullwidth from '../components/fullwidth';
import Textblock from '../components/textblock';
import Card from '../components/card';

const Wrapper = styled.div`
  height: 100%;
  width: 100%;
  padding: 5px 0px;
  position: relative;
  margin: 0 auto;
  max-width: 1366px;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Pixels and Posers</title>
        <meta name="Pixels and Posers" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Wrapper>
       <Bigblock 
        topline='Hello World'
        middleline='welcome to'
        bottomline='my'
        lighttext='world'
       />
       <Primarybutton
        content='Learn More'
       />
      </Wrapper>   
      <Fullwidth bgColor='blend'>
        <h1>Welcome World Travelers</h1>
      </Fullwidth>
      <Fullwidth bgColor='lightgray'>
          <Textblock
            maintext={`Hello <span>World</span> <br/> This is my first line of main-text <br/> And here is another line of main-text`}
            shorttext={`The <span>world</span> is yours for the taking`}
          />
      </Fullwidth>
      <Fullwidth>
        <Card/>
        <Card/>
      </Fullwidth>
    </>
  )
}
