import Head from 'next/head';
import styled from 'styled-components';
import { between } from 'polished';


//between(fromSize: (string | number), toSize: (string | number), minScreen: string, maxScreen: string)
const TextDiv = styled.div`
  font-size: ${between('20px', '100px', '320px', '1200px')};
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      Hello World at 16px
      <TextDiv>
        Hello World
      </TextDiv>
    </>
  )
}
